name: A workflow for ensuring credentials are not in file
'on': push
jobs:
  build:
    name: Cred Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@v0.9i-beta
        with:
          scanArguments: '--regex --entropy=False --max_depth=5 --rules /regexes.json'

